//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPermission
    {
        public ActionPermission()
        {
            this.ActionPermissionRole = new HashSet<ActionPermissionRole>();
        }
    
        public string ActionPermissionId { get; set; }
        public string ParentId { get; set; }
        public string Name { get; set; }
        public bool IsController { get; set; }
        public bool IsAllowedNoneRoles { get; set; }
        public bool IsAllowedAllRoles { get; set; }
        public string ControlName { get; set; }
        public string ActionName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Permission { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsAllowed { get; set; }
    
        public virtual ICollection<ActionPermissionRole> ActionPermissionRole { get; set; }
    }
}
