//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public string BrandID { get; set; }
        public string BrandName { get; set; }
        public int BrandType { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Addr { get; set; }
        public string Url { get; set; }
        public string Linkman { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
