//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileApp
    {
        public string MobileAppID { get; set; }
        public string ApplicationID { get; set; }
        public string MobileClientID { get; set; }
        public string Installer { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> FirstTime { get; set; }
        public Nullable<System.DateTime> SecondTime { get; set; }
        public Nullable<long> Totaltime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> RemoveTime { get; set; }
        public string PackageName { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<bool> IsSys { get; set; }
        public Nullable<int> Frequency { get; set; }
    }
}
