//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneModel
    {
        public string PhoneModelID { get; set; }
        public string DriverID { get; set; }
        public string BrandID { get; set; }
        public string ModelName { get; set; }
        public string System { get; set; }
        public string Version { get; set; }
        public string PictureUrl { get; set; }
        public string MemorySize { get; set; }
        public string CPU { get; set; }
        public string ScreenSize { get; set; }
        public string Resolution { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
